services:
  pedido-receiver:
    build:
      context: .
    container_name: pedido_receiver
    ports:
      - "8080:8080"
    depends_on:
      - pedido-service
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_WEBCLIENT_PEDIDO_URL: http://pedido-service:8080
    restart: always

  pedido-service:
    image: pedido_service:latest
    container_name: pedido_service
    networks:
      - default
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always

networks:
  default:
    name: 7adjt-shopsphere-ms-pedido-service_default
    external: true
